In [48]:
# -*- coding: utf-8 -*-

import pandas as pd
from sarimaxModel import forcastStocks
from loadstocks import loadStocksByTickers
from loadstocks import loadAuNotNaTickersFromYahooExcel
# We will look at stock prices over the past year, starting at January 1, 2016
import datetime
path='/root/pythondev/JanePython/'
inputfile = path+'Yahoo.xlsx'


outputfile = 'stocks2.csv'
savepath=path+outputfile
ds=pd.read_csv(savepath,parse_dates=['Date'],index_col='Date')
print(len(ds.columns))

955

In [49]:
ds.isna().sum().sort_values(ascending=False)
v_columns=ds.columns[ds.isna().sum()<100].tolist()
len(v_columns)

893

In [53]:
end=datetime.date.today()
year=end.year-1

start=datetime.datetime(year,end.month,end.day)
under100=ds[v_columns]
over20columns=under100.columns[under100.isna().sum()>20].tolist()
over20=under100[over20columns]
over20[over20.index>start]

,ZER.AX,SNC.AX,RGP.AX,PRL.AX,CIE.AX,GMY.AX,OHE.AX,IAB.AX,SVS.AX
Date,,,,,,,,,
2018-05-10,0.3850,0.9900,0.065,0.0030,0.987,1.385,0.60,0.410,0.285
2018-05-11,0.3900,0.9550,0.065,0.0030,0.987,1.385,0.60,0.410,0.285
2018-05-14,0.3850,0.9600,0.065,0.0030,0.987,1.390,0.60,0.410,0.285
2018-05-15,0.3850,0.9750,0.069,0.0040,0.987,1.385,0.60,0.390,0.285
2018-05-16,0.3850,0.9750,0.069,0.0035,0.955,1.385,0.60,0.380,0.285
2018-05-17,0.3850,0.9750,0.069,0.0035,0.987,1.400,0.60,0.390,0.285
2018-05-18,0.3850,0.9800,0.069,0.0030,0.987,1.400,0.60,0.390,0.285
2018-05-21,0.3850,0.9800,0.069,0.0030,0.987,1.390,0.60,0.380,0.285
2018-05-22,0.3850,0.9750,0.069,0.0030,0.987,1.390,0.60,0.380,0.285
2018-05-23,0.3850,0.9750,0.069,0.0030,0.987,1.380,0.60,0.420,0.285
2018-05-24,0.3800,0.9700,0.069,0.0030,0.987,1.380,0.60,0.500,0.285
2018-05-25,0.3800,0.9600,0.069,0.0030,0.987,1.380,0.60,0.450,0.285
2018-05-28,0.3800,0.9600,0.069,0.0030,0.987,1.380,0.60,0.460,0.285
2018-05-29,0.3800,0.9700,0.050,0.0030,0.987,1.380,0.60,0.460,0.285
2018-05-30,0.3800,0.9650,0.050,0.0035,0.987,1.380,0.60,0.550,0.285
2018-05-31,0.3800,0.9651,0.055,0.0030,0.974,1.380,0.60,0.550,0.470
2018-06-01,0.4000,0.9650,0.065,0.0030,0.987,1.380,0.68,0.540,0.285
2018-06-04,0.4000,0.9700,0.065,0.0025,0.987,1.400,0.68,0.540,0.285
2018-06-05,0.4000,0.9800,0.065,0.0025,0.987,1.320,0.70,0.590,0.285
2018-06-06,0.4000,0.9700,0.065,0.0025,0.987,1.320,0.70,0.680,0.285
2018-06-07,0.3800,0.9700,0.065,0.0030,0.987,1.320,0.70,0.680,0.285
2018-06-08,0.4000,0.9700,0.065,0.0030,0.987,1.320,0.76,0.640,0.285
2018-06-12,0.4000,0.9600,0.065,0.0030,0.987,1.310,0.77,0.605,0.285
2018-06-13,0.4000,0.9600,0.065,0.0030,0.987,1.350,0.77,0.605,0.285
2018-06-14,0.4000,0.9600,0.065,0.0025,0.987,1.350,0.75,0.590,0.285
2018-06-15,0.4000,0.9650,0.065,0.0025,0.987,1.285,0.75,0.590,0.285
2018-06-18,0.4000,0.9650,0.065,0.0030,0.987,1.270,0.75,0.590,0.285
2018-06-19,0.4000,0.9650,0.065,0.0025,0.987,1.270,0.75,0.590,0.285
2018-06-20,0.3700,0.9650,0.065,0.0025,0.987,1.300,0.75,0.610,0.285
2018-06-21,0.3700,0.9500,0.065,0.0025,0.987,1.300,0.75,0.620,0.285
...,...,...,...,...,...,...,...,...,...
2019-03-25,0.1990,0.8800,NaN,NaN,0.765,NaN,1.13,0.105,NaN
2019-03-26,0.1990,0.8800,NaN,NaN,0.760,NaN,1.13,0.105,NaN
2019-03-27,0.1990,0.8800,NaN,0.0900,0.760,NaN,1.13,0.105,NaN
2019-03-28,0.1990,0.8800,NaN,0.0980,0.770,NaN,NaN,0.105,NaN
2019-03-31,0.2000,0.8650,NaN,NaN,0.770,NaN,NaN,0.105,NaN
2019-04-01,0.1990,0.8750,NaN,NaN,0.755,NaN,NaN,0.105,0.250
2019-04-02,0.2000,0.8800,NaN,NaN,0.755,NaN,NaN,0.105,NaN
2019-04-03,0.2000,0.8800,NaN,NaN,0.765,NaN,NaN,0.105,NaN
2019-04-04,0.2000,0.8850,NaN,NaN,0.750,NaN,NaN,NaN,NaN
2019-04-08,0.1990,0.9050,NaN,NaN,0.765,NaN,NaN,NaN,NaN
2019-04-09,0.2002,0.9700,NaN,NaN,0.750,NaN,NaN,NaN,NaN
2019-04-10,0.2003,0.9050,NaN,NaN,0.770,NaN,NaN,NaN,NaN
2019-04-11,0.2006,0.9100,NaN,NaN,0.755,NaN,NaN,NaN,NaN
2019-04-12,0.1963,0.9100,NaN,NaN,0.760,NaN,NaN,NaN,NaN
2019-04-15,0.1972,0.9150,NaN,NaN,0.780,NaN,NaN,NaN,NaN
2019-04-16,0.1966,0.9150,NaN,NaN,0.780,NaN,NaN,NaN,NaN
2019-04-17,0.1882,0.9100,NaN,NaN,0.765,NaN,NaN,NaN,NaN
2019-04-18,0.1882,0.9100,NaN,NaN,0.775,NaN,NaN,NaN,NaN
2019-04-23,0.1870,0.9100,NaN,NaN,0.775,NaN,NaN,NaN,NaN
2019-04-24,0.1824,0.9150,NaN,NaN,0.780,NaN,NaN,NaN,NaN
2019-04-26,0.1960,0.9150,NaN,NaN,0.765,NaN,NaN,NaN,NaN
2019-04-29,0.1966,0.9000,NaN,NaN,0.785,NaN,NaN,NaN,NaN
2019-04-30,0.1988,0.8900,NaN,NaN,0.790,NaN,NaN,NaN,NaN
2019-05-01,0.1988,0.8750,NaN,NaN,0.790,NaN,NaN,NaN,NaN
2019-05-02,0.2042,0.8750,NaN,NaN,0.780,NaN,NaN,NaN,NaN
2019-05-03,0.2040,0.8900,NaN,NaN,0.780,NaN,NaN,NaN,NaN
2019-05-06,0.2002,0.9000,NaN,NaN,0.790,NaN,NaN,NaN,NaN
2019-05-07,0.1980,0.8900,NaN,NaN,0.800,NaN,NaN,NaN,NaN
2019-05-08,0.3350,0.8850,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-05-09,NaN,NaN,NaN,NaN,0.785,NaN,NaN,NaN,NaN

In [60]:
over20['CIE.AX'].interpolate().bfill()

Date
2017-07-10    1.025000
2017-07-11    1.025000
2017-07-12    1.025000
2017-07-13    1.025000
2017-07-14    1.025000
2017-07-17    1.025000
2017-07-18    1.025000
2017-07-19    1.025000
2017-07-20    1.025000
2017-07-21    1.025000
2017-07-24    1.025000
2017-07-25    1.025000
2017-07-26    1.025000
2017-07-27    1.025000
2017-07-28    1.025000
2017-07-31    1.025000
2017-08-01    1.025913
2017-08-02    1.026826
2017-08-03    1.027739
2017-08-04    1.028652
2017-08-07    1.029565
2017-08-08    1.030478
2017-08-09    1.031391
2017-08-10    1.032304
2017-08-11    1.033217
2017-08-14    1.034130
2017-08-15    1.035043
2017-08-16    1.035957
2017-08-17    1.036870
2017-08-18    1.037783
                ...
2019-03-25    0.765000
2019-03-26    0.760000
2019-03-27    0.760000
2019-03-28    0.770000
2019-03-31    0.770000
2019-04-01    0.755000
2019-04-02    0.755000
2019-04-03    0.765000
2019-04-04    0.750000
2019-04-08    0.765000
2019-04-09    0.750000
2019-04-10    0.770000
2019-04-11    0.755000
2019-04-12    0.760000
2019-04-15    0.780000
2019-04-16    0.780000
2019-04-17    0.765000
2019-04-18    0.775000
2019-04-23    0.775000
2019-04-24    0.780000
2019-04-26    0.765000
2019-04-29    0.785000
2019-04-30    0.790000
2019-05-01    0.790000
2019-05-02    0.780000
2019-05-03    0.780000
2019-05-06    0.790000
2019-05-07    0.800000
2019-05-08    0.792500
2019-05-09    0.785000
Name: CIE.AX, Length: 464, dtype: float64